# Spring configurations
spring:
   main:
      allow-bean-definition-overriding: false
   security:
      require-ssl: false
   # Database
   datasource:
      url: ${JDBC_DATABASE_URL}
      username: ${JDBC_DATABASE_USERNAME}
      password: ${JDBC_DATABASE_PASSWORD}
      
   # JPA properties
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: false
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: true
      
# Server configuration
server:
   port: ${PORT}    
   ssl:
      enabled: false 
      
#angular configuration
angular:
   cross-origin: https://libreria-prisma.herokuapp.com    
      
#Token configuration
jwt:
   secret: secret
   expiration: 36000
