# Spring configurations
spring:
   
   # Database
   datasource:
      url: jdbc:postgresql://localhost:5432/libreria-prisma?useSSL=false
      username: postgres
      password: postgres
      
   # JPA properties
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: false
      generate-ddl: true
      
#angular configuration
angular:
   cross-origin: http://localhost:4200
      
#Token configuration
jwt:
   secret: secret
   expiration: 36000
